<template>
  <q-page>
    <div class='q-pa-md white-font'>
      <h3 class='text-center'>What is our mission ?</h3>
      <div class='row bigger-font'>
        <div class='col-sm-8 offset-sm-2' style='padding-bottom:10px'>
          <p class='subsection-title'>Problem definition</p>
          <p class='text-justify'>
            Academic publishing primarily happens in closed-access journals and is the only system in
            which authors <b>lose all rights</b> to their creations. The current system is certainly not ideal, especially when contrasted with
            other publishing fields such as newspapers, biographies, scripts, plays and novels.
            <br/><br/>
            Scientific publishing is a multi-billion dollar industry in which scientists generate the product and receive no benefit. In
            addition, the top-ranking companies have profits that can go up to 40%, meaning there is a big margin to redirect some of
            these benefits to the scientists. The problem is that there is no platform currently in place that would allow a connection
            between the producer (scientist) and the profits generated by the product (scientific content). What is lacking is a <b>bridge for
            profits to flow directly</b> to the scientist, without the need for a middleman.
            <br/><br/>
            With the growing popularity of open access journals (PLOS publisher), the scientific community seems to recognize that the
            marketization of research has reached a state of oligopoly (few journals with massive influence are able to overprice access
            to research).
            <br/><br/>
            Free-circulating knowledge would allow for different monetization schemes for scientists, something researchers in every
            domain needs. The more funding for research, the better.
            <br/><br/>
            For knowledge to truly become free-circulating, the following 3 criteria need to be met.
          </p>
          <ul>
            <li>
              <p>Researchers should keep ownership of their products.</p>
            </li>
            <li>
              <p>They should be able to reap the benefits of those products when/if they become popular/impactful.</p>
            </li>
            <li>
              <p>The public should have a right to transparent and easy access to the science they helped fund.</p>
            </li>
          </ul>
          <p class='text-justify'>
            The current distribution of scientific knowledge to the world is based on a dual system: (1) Through private publishing groups
            that are in large part closed-access, and (2) with a patent-oriented system which is even more restrictive. We tend to believe
            that there is a better way.
          </p>
        </div>

        <div class='col-sm-8 offset-sm-2'>
          <p class='subsection-title'>Proposed solution</p>
          <p class='text-justify'>
            Scientific results and documents are perceived by scientists as tools used to communicate new discoveries. However, they
            have an additional value for society. Compared to how a biography is a means for an individual to share their thoughts and
            experiences to the public, a scientific article is a tool scientists use to communicate with other scientists, almost exclusively,
            unfortunately due to the very nature of the medium itself. In fact, articles contain opinions, notably in the discussion section
            of a paper. Thus, scientific knowledge has intrinsic value beyond its logical conclusions, meaning a manuscript can be conceptualized
            as a literary document (such as a novel, journal, opinion article or poetry) or even a piece of art (such as
            photography, paintings) crafted to present results in the most honest and unbiased fashion. Like a vintage piece of literature
            or an art collectible, it could be acquired and traded.
            <br/><br/>
            Just as the first X-ray crystallography of DNA by Rosalind Franklin (https://i.stack.imgur.com/8XHZX.jpg) is viewed by many
            as a highly valued collectible, right now, digital content of this sort cannot enjoy the same properties. NFT technology is the
            missing link that would make this possible. How fascinating would it have been if the first paper that coined the name 'CRISPR'
            (dx.doi.org/10.1046/j.1365-2958.2002.02839.x) was minted as an NFT ?
          </p>
          <p class='text-weight-bold text-justify'>
            Manuscripts and other science collectibles can be minted into open science NFTs (osNFTs) and made available to society.
          </p>
          <p class='text-justify'>
            In this model, a scientific document or image would be transformed into an NFT, creating verifiable rights for these digital
            assets. A system based on osNFTs would simultaneously retain the original author's copyright and make the asset a tradable
            product. Pre-set royalties would ensure perpetual revenue streams to the author/lab, where legal entities allow.
            <br/><br/>
            Transforming scientific results into osNFTs would effectively create a bridge between science and society. An asset can be
            acquired from the scientist and traded, establishing a market that would help identify which scientific questions are most
            relevant to society. In other words, supply and demand would generate a new metric by which we measure how society
            perceives a given scientific challenge. Creation of scientific content in this context would now be subject to quasi free-market
            conditions, unshackled from the selfish expectations of centralized entities. It would be a place where the public can have a
            say in the direction of science, effectively leading to a better democratization of it.
            <br/><br/>
            What is needed is a <b>marketplace</b> to make all of this possible.
            <br/><br/>
            There will be at least 2 kinds of osNFTs:
          </p>
          <ol class='text-justify'>
            <li>
              <p>
                <b>Non-monetizable osNFTs</b>: open-access scientific publications, especially those tied to an academic institution,
                may not, at first, be a source of revenue for authors. However, they will still be mintable and tradable. This sounds paradoxical
                at first, because why would anyone trade NFTs if they can't get anything in return? The answer is that money is not the only
                value that can be extracted from such a system. In the academic world, a 'currency' could simply be the scientist or institution's reputation
                and recognition by their peers. This means that osNFTs can become a way for researchers or labs to endorse and signal what they perceive to
                be relevant science. Let's also not forget the 'ethos' of academic research a not-for-profit activity (when talking about individual labs
                of course; universities, publishing companies and networking platforms are a different story).
              </p>
            </li>

            <li>
              <p>
                <b>Monetizable osNFTs</b>: as a collectible, there is inherent value in a document that first reports a new method or discovery
                (historical, legal or religious documents have economic value as collectible items). An original scientific digital asset
                can be owned by someone who either (1) sees value in this item and expects its value to grow or (2) wants to donate
                to the field, and thus receive a 'stamp' which would effectively serve as a proof-of-donation. In the latter scenario, a
                re-sell of the osNFT would not generate income for the buyer (person who donated the money), the money would go
                instead to a treasury that would be used to fund additional research. For authors, using their published academic article might not
                always be an option due to IP laws, but there is no problem with monetizing derivatives of the work. For example, authors can create
                graphical abstracts or summaries of their work, and mint them as osNFTs, which can be bought, traded, and profited from.
              </p>
            </li>
          </ol>
          <p class='text-justify'>
            Additionally, monetizable osNFTs would also include the creation of frameworks for a modular generation of science-inspired NFTs.
            This framework-centric marketplace can be thought of as a meta-NFT marketplace, or a marketplace for building frameworks for creating NFTs.
          </p>
        </div>

        <div class='col-sm-8 offset-sm-2'>
          <p class='subsection-title'>Future outlook</p>
          <p class='text-justify'>
            With time, we can envision a community that will create these generative frameworks but also curate them to ensure scientific rigour. At
            the initial stages of the project, curation will be performed by us, the founding team. Outsourcing to the community will be a gradual process
            that will co-evolve with a DAO (Decentralized Autonomous Organization).
          </p>
        </div>

      </div>
    </div>
  </q-page>
</template>

<script>
export default {

}
</script>
